### ISSUE TITLE
JSON (for strings) >>>>>>>>>>>>>>>>>>>> TS

### ISSUE THREAD

**Issue by x-daniel-17** [TheLimifiedLime/Seashell-Rewrite#2]
put the static regexes in json files instead of TS smh

**Comment by TheLimifiedLime** [comment]
Sure go ahead and submit a pr!

**Comment by x-daniel-17** [comment]
no u

**Comment by TheLimifiedLime** [comment]
I'll close this issue then as this issue isn't high priority. I'll look into it though!

**Comment by x-daniel-17** [comment]
your mom
